# Done
# Chỉ định Maven version mà project sẽ dùng
# Version của maven wrapper
wrapperVersion=3.3.4
# Quy định cách Maven được cung cấp
#bin: tải full Maven
#only-script:chỉ dùng script, tối ưu nhẹ hơn
distributionType=only-script
#Url để tải Maven
distributionUrl=https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.9.12/apache-maven-3.9.12-bin.zip

# Khi chạy ./mvnw clean install -> đọc file này -> Thấy version = 3.9.12 -> Nếu chưa có → download từ URL này
# -> Dùng Maven đó để build
