# Done
# Cấu hình trong môi trường dev
# Nếu key nào không có trong dev profile, Spring Boot vẫn dùng giá trị từ application.properties.
# Không cache file static khi phát triển
spring.resources.cache.period=0
spring.web.resources.cache.cachecontrol.no-store=true

# Tuỳ chọn: bật debug logging cho dev
logging.level.org.springframework=DEBUG
