# Done
# File cấu hình spring boot đọc trước khi ứng dụng chạy



# database init, supports mysql too
# database nằm trong ram, khi app tat, mất toàn bộ dữ liệu
# Ở project này ngoài h2, con có thể dùng mysql. Có thể dùng Laragon để bật mysql và kết nối.
database=h2
# 2 dòng sau bật cấu hình h2-console để xem db
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Product thật sẽ dùng Flyway và Liquibase để tạo và insert dữ liệu
# Tạo bảng
spring.sql.init.schema-locations=classpath*:db/${database}/schema.sql
# Insert dữ liệu
spring.sql.init.data-locations=classpath*:db/${database}/data.sql

# Web
# Mặc định là HTML và HTML la phổ biến nhất
spring.thymeleaf.mode=HTML
spring.thymeleaf.cache=false

# JDBC tích hợp sẵn trong java
# JDBC dùng SQL trực tiếp
# Hibernate là thư viện ngoài khai báo trong pom.xml gọi đến JDBC để connect với DB
# Hibernate Là ORM (Object–Relational Mapping)
# JPA
# Hibernate không tự tạo, sửa hay xoá bảng trong database, mặc định là none
# Ngoài ra còn có update, create, create-drop
spring.jpa.hibernate.ddl-auto=none
# Nên để là false
# Không cho phép Hibernate truy vấn database trong lúc đang render giao diện (View như Thymeleaf)
spring.jpa.open-in-view=false
# convert tên từ camelCase → snake_case khi làm việc với database.
# Nó map tên class + field → tên table + column trong DB
# Tên table  và column trong DB theo cú pháp snake_case(_), còn tên class theo cú pháp lạc đà
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategySnakeCaseImpl
# Hibernate sẽ gom nhiều entity lại để fetch cùng lúc (theo batch), thay vì query từng cái một.
# Giải quyết lỗi n+1 query problem
spring.jpa.properties.hibernate.default_batch_fetch_size=16

# Internationalization
# Tìm các file .properties phục vụ translate (i18n)
spring.messages.basename=messages/messages

# Actuator
# Expose (mở) toàn bộ các endpoint của Spring Boot Actuator ra HTTP
# Không nên cấu hình như này ở production
management.endpoints.web.exposure.include=*

# Logging
# Áp dụng cho toàn bộ package org.springframewor
# log xuất ra console
logging.level.org.springframework=INFO
# logging.level.org.springframework.web=DEBUG
# logging.level.org.springframework.context.annotation=TRACE

# Log ra file
logging.file.name=app.log

# Maximum time static resources should be cached
# server sẽ set max-cache xuống browser thông qua response header
# Trình duyệt sẽ cache (lưu tạm) static resources trong 12 giờ
spring.web.resources.cache.cachecontrol.max-age=12h

# Cau hình này tốt nhất nên để cuối
# Load file application-mysql.properties nhưng nó phải load hết các giá trị trong file này trước
# Nếu key trùng nhau thì file application-mysql.properties sẽ ghi đè giá trị của file này
# kể cả có đặt spring.profiles.active=mysql len đầu
spring.profiles.active=mysql
